from PySide6.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QGroupBox,
    QLabel, QComboBox, QPushButton, QSlider, QDoubleSpinBox,
    QSpinBox, QCheckBox,
)
from PySide6.QtCore import Qt


def build_dolly_tab(ui):
    """Build the Dolly tab and attach widgets to the ui instance."""
    tab = QWidget()
    layout = QVBoxLayout()
    layout.setContentsMargins(10, 12, 10, 10)
    layout.setSpacing(8)

    # ── Track Movement ───────────────────────────────────────────────
    grp_move = QGroupBox("Track Movement")
    gm = QVBoxLayout()
    gm.setSpacing(6)
    ui.dolly_percent_label = QLabel("0.0%")
    ui.dolly_percent_label.setAlignment(Qt.AlignCenter)
    ui.dolly_percent_label.setStyleSheet("color:#e8823c; font-size:13px; font-weight:600;")
    gm.addWidget(ui.dolly_percent_label)
    ui.dolly_slider = QSlider(Qt.Horizontal)
    ui.dolly_slider.setRange(0, 1000)
    ui.dolly_slider.setValue(0)
    gm.addWidget(ui.dolly_slider)
    grp_move.setLayout(gm)
    layout.addWidget(grp_move)

    # ── Track Settings ───────────────────────────────────────────────
    grp_track = QGroupBox("Track Settings")
    gt = QVBoxLayout()
    gt.setSpacing(6)
    length_row = QHBoxLayout()
    lbl_len = QLabel("Length:")
    lbl_len.setObjectName("lbl_section")
    ui.track_length_spinbox = QDoubleSpinBox()
    ui.track_length_spinbox.setRange(10.0, 10000.0)
    ui.track_length_spinbox.setValue(400.0)
    ui.track_length_spinbox.setSuffix(" units")
    ui.update_track_length_btn = QPushButton("↺")
    ui.update_track_length_btn.setFixedSize(24, 24)
    ui.update_track_length_btn.setToolTip("Update track length in scene")
    length_row.addWidget(lbl_len)
    length_row.addWidget(ui.track_length_spinbox)
    length_row.addWidget(ui.update_track_length_btn)
    gt.addLayout(length_row)
    grp_track.setLayout(gt)
    layout.addWidget(grp_track)

    # ── Path Options (Flow / Bank) ───────────────────────────────────
    grp_path_opt = QGroupBox("Path Options")
    gpo = QVBoxLayout()
    gpo.setSpacing(6)

    ui.follow_path_checkbox = QCheckBox("Follow Path (align to path direction)")
    gpo.addWidget(ui.follow_path_checkbox)

    bank_row = QHBoxLayout()
    ui.bank_checkbox = QCheckBox("Bank")
    ui.bank_amount_spin = QDoubleSpinBox()
    ui.bank_amount_spin.setRange(-10.0, 10.0)
    ui.bank_amount_spin.setValue(0.5)
    ui.bank_amount_spin.setDecimals(2)
    ui.bank_amount_spin.setEnabled(False)
    bank_row.addWidget(ui.bank_checkbox)
    bank_row.addWidget(ui.bank_amount_spin)
    gpo.addLayout(bank_row)

    grp_path_opt.setLayout(gpo)
    layout.addWidget(grp_path_opt)

    # ── Orbit / Arc Shot ─────────────────────────────────────────────
    grp_orbit = QGroupBox("Orbit / Arc Shot")
    go = QVBoxLayout()
    go.setSpacing(6)

    radius_row = QHBoxLayout()
    lbl_r = QLabel("Radius:")
    lbl_r.setObjectName("lbl_section")
    ui.orbit_radius_spin = QDoubleSpinBox()
    ui.orbit_radius_spin.setRange(10.0, 5000.0)
    ui.orbit_radius_spin.setValue(300.0)
    ui.orbit_radius_spin.setSuffix(" u")
    ui.update_orbit_radius_btn = QPushButton("↺")
    ui.update_orbit_radius_btn.setFixedSize(24, 24)
    ui.update_orbit_radius_btn.setToolTip("Update orbit radius in scene")
    radius_row.addWidget(lbl_r)
    radius_row.addWidget(ui.orbit_radius_spin)
    radius_row.addWidget(ui.update_orbit_radius_btn)
    go.addLayout(radius_row)

    orbit_btn_row = QHBoxLayout()
    ui.create_orbit_btn = QPushButton("Circle Track")
    ui.create_orbit_btn.setObjectName("btn_primary")
    ui.restore_line_btn = QPushButton("Straight Track")
    orbit_btn_row.addWidget(ui.create_orbit_btn)
    orbit_btn_row.addWidget(ui.restore_line_btn)
    go.addLayout(orbit_btn_row)

    ui.orbit_mode_label = QLabel("Mode: Straight")
    ui.orbit_mode_label.setObjectName("lbl_section")
    ui.orbit_mode_label.setStyleSheet("color:#e8823c; font-size:11px;")
    go.addWidget(ui.orbit_mode_label)

    grp_orbit.setLayout(go)
    layout.addWidget(grp_orbit)

    # ── Custom Path ──────────────────────────────────────────────────
    grp_path = QGroupBox("Custom Path")
    gp = QVBoxLayout()
    gp.setSpacing(6)
    ui.path_combo = QComboBox()
    gp.addWidget(ui.path_combo)
    path_row = QHBoxLayout()
    ui.refresh_paths_btn = QPushButton("Refresh")
    ui.assign_path_btn = QPushButton("Assign to Dolly")
    ui.assign_path_btn.setObjectName("btn_primary")
    path_row.addWidget(ui.refresh_paths_btn)
    path_row.addWidget(ui.assign_path_btn)
    gp.addLayout(path_row)
    grp_path.setLayout(gp)
    layout.addWidget(grp_path)

    # ── Bake Animation ───────────────────────────────────────────────
    grp_bake = QGroupBox("Bake Animation")
    gb = QVBoxLayout()
    gb.setSpacing(6)

    frame_row = QHBoxLayout()
    lbl_sf = QLabel("Start F:")
    lbl_sf.setObjectName("lbl_section")
    ui.ease_start_frame = QSpinBox()
    ui.ease_start_frame.setRange(-10000, 10000)
    ui.ease_start_frame.setValue(0)
    lbl_ef = QLabel("End F:")
    lbl_ef.setObjectName("lbl_section")
    ui.ease_end_frame = QSpinBox()
    ui.ease_end_frame.setRange(-10000, 10000)
    ui.ease_end_frame.setValue(100)
    frame_row.addWidget(lbl_sf)
    frame_row.addWidget(ui.ease_start_frame)
    frame_row.addWidget(lbl_ef)
    frame_row.addWidget(ui.ease_end_frame)
    gb.addLayout(frame_row)

    pct_row = QHBoxLayout()
    lbl_sp = QLabel("From %:")
    lbl_sp.setObjectName("lbl_section")
    ui.ease_start_pct = QDoubleSpinBox()
    ui.ease_start_pct.setRange(0.0, 100.0)
    ui.ease_start_pct.setValue(0.0)
    ui.ease_start_pct.setSuffix("%")
    lbl_ep = QLabel("To %:")
    lbl_ep.setObjectName("lbl_section")
    ui.ease_end_pct = QDoubleSpinBox()
    ui.ease_end_pct.setRange(0.0, 100.0)
    ui.ease_end_pct.setValue(100.0)
    ui.ease_end_pct.setSuffix("%")
    pct_row.addWidget(lbl_sp)
    pct_row.addWidget(ui.ease_start_pct)
    pct_row.addWidget(lbl_ep)
    pct_row.addWidget(ui.ease_end_pct)
    gb.addLayout(pct_row)

    ease_chk_row = QHBoxLayout()
    ui.ease_in_checkbox = QCheckBox("Ease In")
    ui.ease_in_checkbox.setChecked(True)
    ui.ease_out_checkbox = QCheckBox("Ease Out")
    ui.ease_out_checkbox.setChecked(True)
    ease_chk_row.addWidget(ui.ease_in_checkbox)
    ease_chk_row.addWidget(ui.ease_out_checkbox)
    gb.addLayout(ease_chk_row)

    tangent_row = QHBoxLayout()
    lbl_t = QLabel("Tangent:")
    lbl_t.setObjectName("lbl_section")
    ui.ease_tangent_combo = QComboBox()
    ui.ease_tangent_combo.addItems(["Ease (Slow)", "Linear", "Fast", "Smooth"])
    tangent_row.addWidget(lbl_t)
    tangent_row.addWidget(ui.ease_tangent_combo)
    gb.addLayout(tangent_row)

    ui.bake_dolly_btn = QPushButton("Bake Dolly Animation")
    ui.bake_dolly_btn.setObjectName("btn_primary")
    gb.addWidget(ui.bake_dolly_btn)

    grp_bake.setLayout(gb)
    layout.addWidget(grp_bake)

    # ── Bottom ───────────────────────────────────────────────────────
    layout.addStretch()
    ui.reset_dolly_btn = QPushButton("Reset Dolly")
    ui.reset_dolly_btn.setObjectName("btn_danger")
    layout.addWidget(ui.reset_dolly_btn)
    tab.setLayout(layout)
    return tab
